// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzdlelcymdugykzarupn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6ZGxlbGN5bWR1Z3lremFydXBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMDk4NTYsImV4cCI6MjA2NDY4NTg1Nn0.qyjjPatSPveWzStoUuDeIM7LY2crE-pUa3u0HRHFk0o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);